# Generated by Django 4.0 on 2021-12-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickerstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
            ],
        ),
    ]
