# Generated by Django 4.0.2 on 2022-03-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ingestion', '0002_tickerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketcap_colormaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
            ],
        ),
    ]
