# Generated by Django 4.0.2 on 2022-03-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ingestion', '0003_marketcap_colormaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend_colormaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ebitda_colormaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Peratio_colormaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_colormaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
            ],
        ),
    ]
